# Generated by Django 4.2.19 on 2025-03-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('users', '0003_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.developer'),
        ),
    ]
