# Generated by Django 4.2.19 on 2025-03-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_stock_quantity_product_stock'),
        ('users', '0004_profile_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category'),
        ),
    ]
