# Generated by Django 5.1.1 on 2025-03-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_stock_quantity_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
