# Generated by Django 5.1.1 on 2025-03-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
