# Generated by Django 4.2.19 on 2025-04-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
