# Generated by Django 4.2.19 on 2025-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_product_preorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preorder',
            field=models.BooleanField(default=False),
        ),
    ]
