# Generated by Django 4.2.19 on 2025-04-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='end_date',
        ),
        migrations.AddField(
            model_name='rental',
            name='duration',
            field=models.IntegerField(default=True),
        ),
    ]
