# Generated by Django 4.2.19 on 2025-04-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='start_date',
        ),
    ]
